[program:quantllm]
command=/home/groy/miniconda3/envs/quantllm/bin/python /home/groy/quantllm/Demo/step8_vnpy/run.py
user=groy
autostart=true
autorestart=true
startretries=10
startsecs=10
stopwaitsecs=30
stopsignal=TERM
priority=999
stdout_logfile=/home/groy/quantllm/Demo/step8_vnpy/logs/supervisor.out
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile=/home/groy/quantllm/Demo/step8_vnpy/logs/supervisor.err
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
environment=PYTHONUNBUFFERED="1",TZ="Asia/Shanghai"
